Feature: Car quote

Scenario: Without login
	Given I am on the site "https://www.youse.com.br/"
	Then I checked item in main screen
	When I press item by href "/auto/order/new"
	Then I see text "Meu nome é"
	When I enter text "Ayrton França" into "auto_order_flow_lead_person_data_lead_person_attributes_name"
	Then I see text "estou fazendo o seguro"
	When I selected item by name "pra mim" in "auto_order_flow_lead_person_data_insured_person_attributes_same_as_lead_person"
	Then I see text "Se a Youse precisar falar comigo, pode me ligar no"
	When I enter text "11 99999-9999" into "auto_order_flow_lead_person_data_lead_person_attributes_phone"
	Then I see text "ou mandar um e-mail para"
	When I enter text "test_ayrton@gmail.com" into "auto_order_flow_lead_person_data_lead_person_attributes_email"
	When I click button by text "sobre o veículo"
	Then I see text "Meu carro é um"
	When I selected item by name "MINI" in "auto_order_flow_pricing_requirements_vehicle_attributes_make"
		And I selected item by name "COOPER" in "auto_order_flow_pricing_requirements_vehicle_attributes_model"
		And I selected item by name "2016" in "auto_order_flow_pricing_requirements_vehicle_attributes_year"
		And I selected item by name "COOPER 1.5 TURBO 12V 3P AUT. (Gasolina)" in "auto_order_flow_pricing_requirements_vehicle_attributes_version"
	Then I see text "a gente ainda não tá trabalhando com seguros para a marca do seu carro."
	Then I see item by id "emailme"
		And I see text "Quero ser avisado no email"
	When I click button by text "enviar"

Scenario: With login
	Given I am on the site "https://www.youse.com.br/"
	Then I checked item in main screen
	When I perform one login valid
	Then I see text "Seguro Auto"
	When I press item by href "/auto/order/new"
	Then I see text "Meu nome é"
	When I enter text "Ayrton França" into "auto_order_flow_lead_person_data_lead_person_attributes_name"
	Then I see text "estou fazendo o seguro"
	When I selected item by name "pra mim" in "auto_order_flow_lead_person_data_insured_person_attributes_same_as_lead_person"
	Then I see text "Se a Youse precisar falar comigo, pode me ligar no"
	When I enter text "11 99999-9999" into "auto_order_flow_lead_person_data_lead_person_attributes_phone"
	Then I see text "ou mandar um e-mail para"
	When I enter text "test_ayrton@gmail.com" into "auto_order_flow_lead_person_data_lead_person_attributes_email"
	When I click button by text "sobre o veículo"
	Then I see text "Meu carro é um"
	When I selected item by name "MINI" in "auto_order_flow_pricing_requirements_vehicle_attributes_make"
		And I selected item by name "COOPER" in "auto_order_flow_pricing_requirements_vehicle_attributes_model"
		And I selected item by name "2016" in "auto_order_flow_pricing_requirements_vehicle_attributes_year"
		And I selected item by name "COOPER 1.5 TURBO 12V 3P AUT. (Gasolina)" in "auto_order_flow_pricing_requirements_vehicle_attributes_version"
	Then I see text "a gente ainda não tá trabalhando com seguros para a marca do seu carro."
		And I see text "Quero ser avisado no email"
		And I see item by id "emailme"
	When I enter text "ayrtonfranca@gmail.com" into "emailme"
	When I click button by text "enviar"